name: callor_demo
description: How to use Callor package effectively.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0
homepage: https://dartoos.dev
repository: https://github.com/dartoos-dev/callor

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  callor:
    path: ../
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.5.3

flutter:
  uses-material-design: true
