name: formdator
description: A formidable collection of Flutter form field validators that can be selected and grouped into various combinations through composition — Decorator Pattern.
version: 0.8.2
homepage: https://dartoos.dev
repository: https://github.com/dartoos-dev/formdator

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.5.3
