name: callor
description: Declarative, composable, object-oriented set of Flutter form validators.
version: 0.1.3
homepage: https://dartoos.dev
repository: https://github.com/dartoos-dev/callor

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cpf_cnpj_validator: ^2.0.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.5.3
