name: formdator
description: A collection of form field validators that can be selected and grouped into various combinations through composition — Decorator Pattern.
version: 1.1.0
homepage: https://dartoos.dev
repository: https://github.com/dartoos-dev/formdator

environment:
  sdk: ">=2.12.0 <3.0.0"

dev_dependencies:
  lint: ^1.8.1
  test: ^1.17.12
